import { build } from "esbuild";

await build({
  entryPoints: ["src/index.js"],
  bundle: true,
  format: "iife",
  target: ["es2020"],
  outfile: "ha-raven-house-cards.js",
  legalComments: "none",
  sourcemap: false,
  minify: false,
  charset: "utf8",
  banner: {
    js: "// HACS dashboard bundle entrypoint file.\n// Auto-generated from src/. Do not edit this file directly.",
  },
});
